FROM registry.centos.org/centos/centos:7

MAINTAINER Jyasveer Gotta <jgotta@redhat.com>

RUN mkdir -p /opt/scripts /var/www/html

ENV STACK_API_TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIwbEwwdlhzOVlSVnFaTW93eXc4dU5MUl95cjBpRmFvemRRazlyenEyT1ZVIn0.eyJqdGkiOiI4YzgyMjM0OS03ZWNkLTQ5NDItOTgzYy01NjI1NTJlYTcwM2YiLCJleHAiOjE1MzMzODcwNTEsIm5iZiI6MCwiaWF0IjoxNTAxODUxMDUxLCJpc3MiOiJodHRwczovL3Nzby5vcGVuc2hpZnQuaW8vYXV0aC9yZWFsbXMvZmFicmljOCIsImF1ZCI6ImZhYnJpYzgtb25saW5lLXBsYXRmb3JtIiwic3ViIjoiNGU3YzY5MjEtZDJjYi00MjMyLWJjYjQtMjQzZGFiNjNiZDJkIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiZmFicmljOC1vbmxpbmUtcGxhdGZvcm0iLCJhdXRoX3RpbWUiOjAsInNlc3Npb25fc3RhdGUiOiIyZjQzNGFjZC1iZjMyLTRhOGQtODFmNi1lNjQ1ZGRkMjkwZjYiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJicm9rZXIiOnsicm9sZXMiOlsicmVhZC10b2tlbiJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwicHJlZmVycmVkX3VzZXJuYW1lIjoiYmF5ZXNpYW4tYXBpIn0.Io54Edr7BgHBG3LMIrI4dhK7UKaEPAeNL8ZFzIOEwTtFjj4BFWQOmq4eQI6toAplCF6-TNROzcdVrJSXCSBeq0vHQ-i9Hbo0XTWqcbvqMqyBlunmD1Wk-llkn6UXKQaBC4xJPktA7qtOJ3NYxxBp4nR0MZ4UUpBO1sUg8SwENAKp45-WnWeUDlKPmEqLCBI-1R4HmHh3Juxr1jTqlDk3JZEUnuDH835LfB5I_LOh1xVudb3ssU7gyCd1W7KRW6AKqfJat0oWOpoUbJYPrtK4gp4NlB5VgmvKsJ9RKHf6xWWeS0y2RC0H6jTakoAy9MQ9eaARuM4YfvmbIl2UUmuLeQ

ADD dist /var/www/html/

ADD ./fix-permissions.sh ./install.sh ./passwd.template ./run.sh /opt/scripts/

RUN chmod -R 777 /opt/scripts && . /opt/scripts/install.sh

WORKDIR /var/www/html

EXPOSE 8080 8443

USER apache

ENTRYPOINT ["/opt/scripts/run.sh"]
CMD ["apache"]
