# base image sources https://github.com/rhdt/EL-Dockerfiles/tree/master/base/fabric8-analytics-stack-report-ui

FROM prod.registry.devshift.net/osio-prod/base/fabric8-analytics-stack-report-ui:latest

RUN mkdir -p /opt/scripts /var/www/html

ADD dist /var/www/html/

ADD ./passwd.template ./run.sh /opt/scripts/

RUN chmod -R 777 /opt/scripts/run.sh

WORKDIR /var/www/html

EXPOSE 8080 8443

USER apache

ENTRYPOINT ["/opt/scripts/run.sh"]

CMD ["apache"]
